// Generated by scripts/extract-existing-data.mjs from 日暮途远.html.
// Re-run the script when the legacy single-file HTML is the source of truth.

export const site = {
  "title": "日暮途远",
  "subtitle": "马瘦毛长",
  "intro_lines": [
    "22 岁，还在赶路的学生。",
    "写过两本小说集、两本在写的长篇、",
    "做过几个项目，夜里基本不睡。",
    "这里堆着我做过的东西、写过的字，",
    "和一些没处安放的话。"
  ],
  "hero_quote": [
    "我是堂吉诃德。",
    "我准备发起今天的冲锋。"
  ],
  "hero_from_label": "《虽然歌声无形》开篇",
  "hero_target": {
    "kind": "collection-piece",
    "col": "col-zhi",
    "piece": "songsheng"
  },
  "handle": "@student-agent",
  "github": "https://github.com/student-agent",
  "email": "hi@example.com"
} as const;

export const projects = [
  {
    "id": "eatconfusion",
    "name": "吃惑",
    "sub": "AI 智能膳食管理 App",
    "tags": [
      "AI",
      "全栈",
      "比赛"
    ],
    "status": "参赛中",
    "year": "2025",
    "desc": "用 AI 接管「今天吃啥」——拍照识别热量、清空冰箱一键生成菜谱、农产品溯源、还有一个会说人话的 AI 饭搭子。",
    "stack": "Taro · React · Spring Boot · LangChain4j · Qwen-VL",
    "github": "https://github.com/student-agent/eatconfusion"
  },
  {
    "id": "student-agent",
    "name": "student-agent",
    "sub": "会自学的学习型 Agent",
    "tags": [
      "AI",
      "Python",
      "Agent"
    ],
    "status": "开发中",
    "year": "2025",
    "desc": "让模型像学生一样学习——遇到不会的就去查、查完动手做、做完回头检查对不对、错了再来一次。",
    "stack": "Python · LLM · Tool-Use · ReAct",
    "github": "https://github.com/student-agent"
  }
] as const;

export const collections = [
  {
    "id": "col-zhi",
    "name": "致",
    "dedication": "致所有我爱和爱我的人",
    "note": "我把它的第一篇留给我那时最亲爱的人。",
    "order": 0,
    "preface": {
      "title": "前言",
      "body": [
        "                    前言 这篇文章本应该有个不一样的前言，也本该有个不一样的内容。在我纠结如何为《致》收尾时，我仍旧被上一段感情的阴影缠绕着。我在那篇前言中曾这般写到——“我把《致》的第一篇留给我那时最亲爱的宝宝，而现在我应该叫她什么呢？只是短暂驻留的候鸟小姐，曾一度洒在我脸上温柔的月光，我当前人生中最沉重的遗憾，或者只是简单的“前女友”三个字。",
        "我无比期望我能衷心地说出最后一个，可令人无奈的是，我的生活一直徘徊在前三者中，直到现在也还没能释怀。” 我那时本想把我那段曲折离奇的恋爱直接写成小说的形式，因为那段的感情的确是我曾拥有过最热烈最纠结的感情，但直到现在，在我不再为我的前任而暗自神伤之时。我才意味到，即使我把这段我感受最明显的爱写成文字，也无以表达我对我爱和爱我的人的情感。这份感情已经掺杂了太多东西，我不会再把我和她的故事作为这篇小说的主线。 我想对那些抱有真挚感情的人传达的应该是我的企盼，我对未来的愿望，我对“从今往后”这四个字不是抱有悲观态度的决心。 唯有如此，我才能唱着无形的歌，用着单薄的文字，直到把这份情感，传达给所有我爱，和爱我的人。"
      ]
    },
    "prefaceOld": {
      "title": "原前言（2022 旧版）",
      "body": [
        "                                   前言 我很少写前言，可是这篇作品我却又有太多话想写在前面，写给自己，也写给或许会看到这篇作品的人。 这篇作品开篇于一个很糟糕的情况下，我的心情类似于扉页开篇时，未曾想到，过了五年，我兜兜转转又回到此处。 我把《致》的第一篇留给我那时最亲爱的宝宝，而现在我应该叫她什么呢？只是短暂驻留的候鸟小姐，曾一度洒在我脸上温柔的月光，我当前人生中最沉重的遗憾，或者只是简单的“前女友”三个字。 我无比期望我能衷心地说出最后一个，可令人无奈的是，我的生活一直徘徊在前三者中，直到现在也还没能释怀。 我曾经把《扉页》投给过杂志，被退了回来，当时的编辑说我的小说就像是日记一般。那时我并未谈过一次恋爱，只是把恋爱的幻想投入到了小说中，现在想来，或许这样的评价也是一种夸奖也说不定。至少日记的真实与代入感都尚且不错。 不过我其实更想试试要不要真的把自己的恋爱的好多情节写到小说里，于是丢弃掉了尚不完整的初案，准备提笔写下这篇《虽然歌声无形》，以致给所有我爱和爱我的人。 祝他们总能幸福，当然，希望我也是。"
      ]
    }
  },
  {
    "id": "col-youhua",
    "name": "油画",
    "dedication": "",
    "note": "一些慢一点的画面。",
    "order": 1,
    "preface": null,
    "prefaceOld": null
  }
] as const;

export const novels = [
  {
    "id": "novel-miso",
    "title": "请每天早上为我做味增汤吧",
    "subtitle": "一个三无少女入侵我的生活的故事",
    "status": "连载中",
    "date": "2025 — ",
    "synopsis": "\"我\"是高中走读生零绮一，一个自我标榜失败者的二次元爱好者；偶遇异色瞳的洛灵梦，把她接回家，从此每天早上要求被做一碗味增汤。校园恋爱轻喜剧。",
    "order": 0,
    "chapters": [
      {
        "slug": "00-chapter-0",
        "title": "楔子",
        "order": 0
      },
      {
        "slug": "01-chapter-1",
        "title": "第一章 总之我和她平淡无奇的开局就是这样",
        "order": 1
      },
      {
        "slug": "02-chapter-2",
        "title": "第二章 这个是三无吗",
        "order": 2
      },
      {
        "slug": "03-chapter-3",
        "title": "第三章 我真的无人能敌",
        "order": 3
      },
      {
        "slug": "04-chapter-4",
        "title": "第四章 所以为什么住我家要我负责啊",
        "order": 4
      },
      {
        "slug": "05-chapter-5",
        "title": "第五章 泡面十级大师",
        "order": 5
      },
      {
        "slug": "06-chapter-6",
        "title": "第六章 学习这婊砸",
        "order": 6
      },
      {
        "slug": "07-chapter-7",
        "title": "第七章 夜袭是不可能夜袭的",
        "order": 7
      },
      {
        "slug": "08-chapter-8",
        "title": "第八章 “好吃的，不给我，可恶”",
        "order": 8
      },
      {
        "slug": "09-chapter-9",
        "title": "第九章 失败者理论",
        "order": 9
      },
      {
        "slug": "10-chapter-10",
        "title": "第十章 屈人之威！",
        "order": 10
      },
      {
        "slug": "11-chapter-11",
        "title": "第十一章 食堂里的战争",
        "order": 11
      },
      {
        "slug": "12-chapter-12",
        "title": "第十二章 给三无少女买衣服是什么大型直播节目",
        "order": 12
      },
      {
        "slug": "13-chapter-13",
        "title": "第十三章 三无少女的收视率",
        "order": 13
      },
      {
        "slug": "14-chapter-14",
        "title": "第十四章 灾难进化论",
        "order": 14
      },
      {
        "slug": "15-chapter-15",
        "title": "第十五章 旁观者的提问与我不打算回答的那些事",
        "order": 15
      },
      {
        "slug": "16-chapter-16",
        "title": "第十六章 超市猎场与人类采购行为观察报告",
        "order": 16
      },
      {
        "slug": "17-chapter-17",
        "title": "第十七章 厨房攻防战与无法归档的感知残留",
        "order": 17
      },
      {
        "slug": "18-chapter-18",
        "title": "第十八章 我打外卖？真的假的？",
        "order": 18
      },
      {
        "slug": "19-chapter-19",
        "title": "第十九章 两周败绩与蹲守成功的概率论",
        "order": 19
      },
      {
        "slug": "20-chapter-20",
        "title": "第二十章 监工、漏洞与不甘心的撤退",
        "order": 20
      },
      {
        "slug": "21-chapter-21",
        "title": "第二十一章 食材采购与不必要的观察记录",
        "order": 21
      },
      {
        "slug": "22-chapter-22",
        "title": "第二十二章 零绮一的料理革命（继续升级未遂）",
        "order": 22
      }
    ]
  },
  {
    "id": "novel-weird",
    "title": "请别再让我的生活更奇怪了",
    "subtitle": "武术世家大小姐高考完跑去环游世界",
    "status": "一章完",
    "date": "2024 — ",
    "synopsis": "李慕凝，武术天赋最高的大小姐，被家族日复一日训练到想逃。高考后甩开父母，独自环球旅行。",
    "order": 1,
    "chapters": [
      {
        "slug": "00-chapter-0",
        "title": "人设速写",
        "order": 0
      },
      {
        "slug": "01-chapter-1",
        "title": "第一章 送别",
        "order": 1
      }
    ]
  }
] as const;
